### ISSUE TITLE
README文档感觉说明不是很清楚，对于初接触的人来说不知道该怎么用

### ISSUE THREAD

**Issue by fanKarl** [LightSun/android-drag-FlowLayout#3]
看了作者的文档，很多地方都搞不清楚例如：
1、刚接触一看不知道怎么引用，（我是在简单看了源码之后才知道要在XML里面引用，也就是自定义的View），但是README文档里一直在强调Java代码的东西
2、能不能定义自己的Adapter，这里我猜测应该是继承DragAdapter，但是里面的方法就不知道具体表达什么意思了，源码里面也只是抽象方法，我个人能力有限，真的不知道该怎么用。
3、还有那个预存Item是什么意思？
这只是我个人的一些看法，可能是因为个人水平比较低导致消化不良，如果可以，希望作者能费一些时间解答一下这些，谢谢！

**Comment by LightSun** [comment]
好的。多谢提醒

**Comment by LightSun** [comment]
第1,  2 个 问题。马上补上。
第3个问题。  意思就是view的重复使用问题。避免多次重新创建。

**Comment by LightSun** [comment]
已在文档中对adapter的方法添加了说明，如果还有问题。可以随时问我
