### ISSUE TITLE
设置DragFlowLayout宽高都为match_parent，item子项新增加的会重叠起来。

### ISSUE THREAD

**Issue by fanKarl** [LightSun/android-drag-FlowLayout#4]
我开始把xml布局DragFlowLayout宽高设置为match_parent，但是addItem一直加不上，仔细观察才发现其实是因为没个新增加的item都覆盖在了前一个item上面，所以看起来只有一个item在变化。
但是把DragFlowLayout的宽高改成wrap_content就可以正常实现了，不知道是作者故意这么设置的还是设计的问题呢？

**Comment by fanKarl** [comment]
还有一个问题，当我增加了一个item我要怎么拿到增加的这个item的下标呢？拖拽改变顺序以后新的下标又该怎么得到呢？

**Comment by LightSun** [comment]
1, 第一个问题和测量布局有关。稍后我会看看。
2，第2个问题，你可以说吓你的具体需求么？ 为什么需要新的下标。（公司项目里我也用了我这库的哈）

**Comment by fanKarl** [comment]
关于第二个问题：既然标签能够拖拽排序了，肯定想要记住标签的顺序，这样才能在其他页面按照这个页面排序使用，另外如果这是标签订阅功能，那么当取消订阅的时候要把当前标签返回到未订阅标签栏某个位置，可能是该标签之前未订阅时候的位置。大概是这个意思，。

**Comment by LightSun** [comment]
标签的顺序， 直接通过 mDragflowLayout.getDragItemManager().getItems() 获取到所有标签list。  订阅->未订阅 就是点击删除嘛。关于你说的 “另外如果这是标签订阅功能，那么当取消订阅的时候要把当前标签返回到未订阅标签栏某个位置，可能是该标签之前未订阅时候的位置。” 这句话的意思是否是 还原到订阅之前的状态？

**Comment by fanKarl** [comment]
就是另外还有一个ListView专门放所有未订阅标签，取消订阅那该标签在未订阅列表里重新出现

**Comment by LightSun** [comment]
拖拽流布局里面的标签 一般都是订阅了的。未订阅的标签属于额外的逻辑。最好的话。自己维护一个。我这边都是自己维护的

**Comment by fanKarl** [comment]
恩，好的，谢谢解答~

**Comment by LightSun** [comment]
客气了。
