### ISSUE TITLE
error message "package android.support.annotation does not exist"

### ISSUE THREAD

**Issue by dbdevtop** [LightSun/android-drag-FlowLayout#5]
I get this error message when trying to build a wrapper with the RAD tool "[B4X]([https://www.b4x.com/android/forum/threads/tool-simple-library-compiler-build-libraries-without-eclipse.29918/#content])"

Can you help me to figure out what I have to do?

**Comment by LightSun** [comment]
you can see it in here .[http://stackoverflow.com/questions/36906095/error28-34-error-package-android-support-annotation-does-not-exist](url) , wish it can help you.

**Comment by Manish095sharma** [comment]
error message "package android.support.annotation does not exist


getting this error please help me out
