### ISSUE TITLE
旋转屏幕，生命周期变化导致数据全部抹除

### ISSUE THREAD

**Issue by hpuhsp** [LightSun/android-drag-FlowLayout#6]
如果都是最后一个lable位置放不下，直接切换到下一行，当每行空余长度大于总长度30percent时，是否考虑次行所有标签居中显示，否则每行最后留白，这样的排版个人觉得不太好

**Comment by LightSun** [comment]
抱歉，才看到。1， 生命周期变化导致数据全部抹除， 这个问题马上处理。2  是否考虑次行所有标签居中显示，当每行空余长度大于总长度30percent时. 这个问题需要慎重考虑下

**Comment by denbard** [comment]
现在这个布局还在维护么？比较想使用，但是发现已经8个月没有过提交了

**Comment by LightSun** [comment]
@denbard 你有什么新需求？ 随时可以维护

**Comment by LightSun** [comment]
closed after two weeks
