### ISSUE TITLE
com.heaven7.memory.util.Cacher  not found

### ISSUE THREAD

**Issue by dbdevtop** [LightSun/android-drag-FlowLayout#7]
I try to wrap your wonderful lib to a RAD software called "B4X".

I get this compiling error:

`Starting step: Compiling Java code.
javac 1.8.0_73
D:\_B4A_SAMPLES\_LibsToWrap\_temp\src\java\com\heaven7\android\dragflowlayout\DefaultDragCallback.java:9: error: package com.heaven7.memory.util does not exist
import com.heaven7.memory.util.Cacher;

Am I missing something?

**Comment by LightSun** [comment]
sorry  i had saw it too late, have you fixed it ?
