### ISSUE TITLE
DragFlowLayout inside a Scrollview not working properly

### ISSUE THREAD

**Issue by akhilesh9205** [LightSun/android-drag-FlowLayout#8]
I have placed DragFlowLayout inside of a Scrollview. DragflowLayout is filled with childs (tags) such that height of the DragflowLayout is greater than device screen height.

For the first time when i scroll the Scrollview , its work perfectly. But as i first drag and drop a child inside DragFlowLayout and after that if i try to scroll the Scrollview then scrolling does not work.

same issue is also in the Sample provided in repo.

Please help.

**Comment by akhilesh9205** [comment]
help

**Comment by LightSun** [comment]
because the  touch event is consumed by DragFlowLayout . if you touch outside the tags .it can
