### ISSUE TITLE
没有长按的情况下（删除按钮不出现），单独的item点击事件没有做处理

### ISSUE THREAD

**Issue by ltym2016** [LightSun/android-drag-FlowLayout#9]
没有长按的情况下（删除按钮不出现的情况），单独的item点击事件没有做处理？

**Comment by LightSun** [comment]
目前确实没处理。 你有这个需求？

**Comment by LightSun** [comment]
这个本来就是编辑标签用的。

**Comment by ltym2016** [comment]
是的，需要点击跳转到相应的内容，例如今日头条，网易新闻



发自我的小米手机在 LightSun <notifications@github.com>，2017年6月29日 上午11:08写道：目前确实没处理。 你有这个需求？

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/LightSun/android-drag-FlowLayout","title":"LightSun/android-drag-FlowLayout","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/LightSun/android-drag-FlowLayout"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LightSun in #9: 目前确实没处理。 你有这个需求？"}],"action":{"name":"View Issue","url":"https://github.com/LightSun/android-drag-FlowLayout/issues/9#issuecomment-311850213"}}}

**Comment by LightSun** [comment]
这样使用即可。不过需要注意。自己要去处理点击标签和非标签的情况
 mDragflowLayout.setOnItemClickListener(new DragFlowLayout.OnItemClickListener() {
            @Override
            public boolean performClick(DragFlowLayout dragFlowLayout, View child, MotionEvent event, int dragState) {
                Logger.w(TAG,"performClick","");
                return true;
            }
        });
